title: illallangi.dn42
owner: Andrew Cole
email: andrew.cole@illallangi.com
description: >-
  Experimental Networking
baseurl: ""
url: "https://dn42.illallangi.enterprises"
twitter_username: "illallangi"
github_username:  "illallangi"
color1: "#5C258D"
color2: "#4389A2"